name: generate snake
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: SEU_USUARIO
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
      - uses: actions/checkout@v4
      - name: Push to output branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin output || git branch -f output
          git checkout output || git checkout -b output
          mkdir -p .
          cp -f dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          git add github-contribution-grid-snake.svg
          git commit -m "update snake" || true
          git push -f origin output
